### PR TITLE
[#33] No longer supply stlib paths 

### LINKED ISSUE #33: Fix so that we no longer need to supply the path to C++ stdlib

### LINKED ISSUE #37: Fix workflow error on obtain_an_build_vsomeip
workflow job obtain_and_build_vsomeip fails:

``` bash
   inlined from ‘void vsomeip_v3::routing_manager_client::on_update_security_credentials(const vsomeip_v3::protocol::update_security_credentials_command&)’ at /home/runner/work/up-transport-vsomeip-rust/up-transport-vsomeip-rust/vsomeip-src/implementation/routing/src/routing_manager_client.cpp:2839:27:
/usr/include/boost/icl/detail/interval_set_algo.hpp:358:5: error: writing 9 bytes into a region of size 8 [-Werror=stringop-overflow=]
  358 |     const_cast<value_type&>(key_value<Type>(first_))
      |     ^~~~~~~~~~
/home/runner/work/up-transport-vsomeip-rust/up-transport-vsomeip-rust/vsomeip-src/implementation/routing/src/routing_manager_client.cpp: In member function ‘void vsomeip_v3::routing_manager_client::on_update_security_credentials(const vsomeip_v3::protocol::update_security_credentials_command&)’:
/home/runner/work/up-transport-vsomeip-rust/up-transport-vsomeip-rust/vsomeip-src/implementation/routing/src/routing_manager_client.cpp:2835:44: note: at offset 40 into destination object ‘its_gid_set’ of size 48
 2835 |         boost::icl::interval_set<uint32_t> its_gid_set;
      |                                            ^~~~~~~~~~~
cc1plus: all warnings being treated as errors
gmake[2]: *** [CMakeFiles/vsomeip3.dir/build.make:1129: CMakeFiles/vsomeip3.dir/implementation/routing/src/routing_manager_client.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:852: CMakeFiles/vsomeip3.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
Error: Process completed with exit code 2.
```
reference:
https://github.com/eclipse-uprotocol/up-transport-vsomeip-rust/actions/runs/11936008823/job/34217646323

### PR DESCRIPTION
**Pull request by dmacattack**
* add buildenv.sh & update workflows to set the c++ paths
* update READMEs accordingly
* decrease test iterations for efficient tests
* fix runner version to ubuntu 22.04
* add workflow build dependencies

closes #33 
closes #37

### CODE REVIEW

**Comment by PLeVasseur** [comment]
Hey @dmacattack -- thanks for the contribution! Is there any way to incorporate this into the CI to ensure that it's used as a part of it and validated?

**Comment by dmacattack** [comment]
opening this PR. seems like obtain_and_build_vsomeip is failing just like it did on PR #35 
https://github.com/eclipse-uprotocol/up-transport-vsomeip-rust/actions/runs/11936008823/job/34217646323

I'll create an issue for this

**Comment by dmacattack** [comment]
I went back in the history of this project and found the ones that succeeded were in fact ubuntu 22.04. I dont have 24 installed, but I would bet vsomeip doesnt build on it either (not just a workflow issue). 
Ubuntu changes dependent libs here and there, not uncommon. So likely, theres a dependency not quite resolved, and yes I burned a lot of githubs time to find this. Sorry about that.

**Comment by PLeVasseur** [comment]
Hey @dmacattack -- thanks for troubleshooting! I'll put some time aside to review :)

File: up-transport-vsomeip/tests/point_to_point.rs [hunk 1]
```diff
@@ -453,7 +453,7 @@ async fn point_to_point() {
     let start_time = Instant::now();
 
     let mut iterations = 0;
-    while Instant::now().duration_since(start_time) < duration {
+    while (Instant::now().duration_since(start_time) < duration) && (iterations < MAX_ITERATIONS) {
```
Comment (PLeVasseur) [inline up-transport-vsomeip/tests/point_to_point.rs:456]: IIRC the issue here you found was that without bounding the iterations we're saturating the TCP/IP connection, potentially leading to packets that take "too long" to arrive, right?

I think it'd be good to make a note of why the iteration bound was added in each file as a comment so we don't forget and add this problem back in.

File: vsomeip-sys/README.md [hunk 2]
```diff
@@ -13,18 +13,16 @@ We currently support vsomeip **3.4.10** as released [here](https://github.com/CO
...
 2. Ensure you have the vsomeip library installed (optional, see features in `Cargo.toml`)
 3. Ensure that you have the [requirements](https://github.com/COVESA/vsomeip?tab=readme-ov-file#build-instructions-for-linux) of the vsomeip project install
+4. Run env_setup.sh in parent directory
 
-Then,
-
-```bash
-VSOMEIP_INSTALL_PATH=<path/to/where/to/install/vsomeip> GENERIC_CPP_STDLIB_PATH=<path/to/generic/cpp/stdlib> ARCH_SPECIFIC_CPP_STDLIB_PATH=<path/to/arch_specific/cpp/stdlib> cargo build
+``` bash
+source ../build/env_setup.sh
```
Comment (PLeVasseur) [inline vsomeip-sys/README.md:19]: I think you changed the shell script name after writing this line probably.

```suggestion
source ../build/envsetup.sh
```

File: vsomeip-sys/README.md [hunk 3]
```diff
@@ -13,18 +13,16 @@ We currently support vsomeip **3.4.10** as released [here](https://github.com/CO
...
 ```
 
-If you are running a Linux-based OS on x86_64, it's possible these look like:
+Then,
 
-```
-GENERIC_CPP_STDLIB_PATH=/usr/include/c++/11
-ARCH_SPECIFIC_CPP_STDLIB_PATH=/usr/include/x86_64-linux-gnu/c++/11
+```bash
+VSOMEIP_INSTALL_PATH=<path/to/where/to/install/vsomeip> cargo build
```
Comment (PLeVasseur) [inline vsomeip-sys/README.md:25]: This is building using the `bundled` feature, so we don't need this environment variable set in this case.

```suggestion
cargo build
```

There's a section down below that explains `VSOMEIP_INSTALL_PATH` can be optionally set to install vsomeip at that location.

File: vsomeip-sys/README.md [hunk 4]
```diff
@@ -61,7 +59,7 @@ The `VSOMEIP_INSTALL_PATH` then becomes _required_ and must point to the install
 
 You may do the following (note `--no-default-features`):
 ```bash
-VSOMEIP_INSTALL_PATH=<path/to/where/to/install/vsomeip> GENERIC_CPP_STDLIB_PATH=<path/to/generic/cpp/stdlib> ARCH_SPECIFIC_CPP_STDLIB_PATH=<path/to/arch_specific/cpp/stdlib> cargo build --no-default-features
+VSOMEIP_INSTALL_PATH=<path/to/where/to/install/vsomeip> cargo build --no-default-features
```
Comment (PLeVasseur) [inline vsomeip-sys/README.md:62]:
```suggestion
VSOMEIP_INSTALL_PATH=<path/to/where/vsomeip/is/installed> cargo build --no-default-features
```

File: .github/workflows/bundled-lint-and-test.yaml [hunk 5]
```diff
@@ -36,9 +35,35 @@ concurrency:
...
+        id: set_env
+        run: |
+          source ./build/envsetup.sh highest
+          echo "arch_specific_cpp_stdlib_path=$ARCH_SPECIFIC_CPP_STDLIB_PATH" >> $GITHUB_OUTPUT
+          echo "generic_cpp_stdlib_path=$GENERIC_CPP_STDLIB_PATH" >> $GITHUB_OUTPUT
+
   lint:
     name: Lint
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
```
Comment (PLeVasseur) [inline .github/workflows/bundled-lint-and-test.yaml:61]: Note that I opened #38 in which it's shown by @dmacattack on a possible work-around vsomeip has suggested.

We should address this in a follow-up PR.

**Review by PLeVasseur — CHANGES_REQUESTED** [review]
Hey @dmacattack -- thanks for doing the troubleshooting around Boost in this PR too!

I left a few suggestions. Could you take a look?

File: up-transport-vsomeip/tests/point_to_point.rs (hunk 1 above)
Comment (dmacattack) [reply up-transport-vsomeip/tests/point_to_point.rs:456]: good call I can add that comment, and yes. On my local machine I found the network buffer to be full, and the TCP retransmissions were constantly being requested. With an absurd delay for the test, it did work, but we dont need this amount of data to validate the test.

**Review by PLeVasseur — APPROVED** [review]
Great! LGTM

Can you squash to one commit and we'll merge?

File: .github/workflows/bundled-lint-and-test.yaml [hunk 6]
```diff
@@ -36,9 +35,35 @@ concurrency:
 
 jobs:
 
+  set-env:
+    name: Set environment variables
+    runs-on: ubuntu-22.04
```
Comment (PLeVasseur) [inline .github/workflows/bundled-lint-and-test.yaml:40]: Link for @olitha
